### ISSUE TITLE
Bug: total number of worker with disabilities must conform to policy. 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#527] opened 2017-12-21 21:49 UTC
Bug description: currently we can enter large number, example 50000. 
@EStriegel Liz, what is allowable range per policy for this field?  

![image](https://user-images.githubusercontent.com/25330625/34276343-022a8afa-e66f-11e7-836e-cfe75c473f0c.png)

**Comment by EStriegel** [comment] 2017-12-28 20:11
Closing as this is not a bug.

**Closed by EStriegel** 2017-12-28 20:11 UTC
Labels: bug, Major, WHD QA
