### ISSUE TITLE
Employee Information Screen UX: mouse scroll causes information changes

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#620] opened 2018-02-08 18:22 UTC
Do not allow scroll mouse to change information – example: employee information screen: numbers adjusted if scroll down before clicking on blank part of screen.

**Comment by joebhaktiarDOL** [comment] 2018-03-19 16:25
I need more details on this bug, how can i replicate it?

**Comment by EStriegel** [comment] 2018-03-19 16:41
@joebhaktiarDOL Please see screenshot below.  If you go to the Employer page, and scroll down to the question, you'll see when you enter a number, small up and down arrows appear in the field.  If you hover your mouse over the field when it is selected, and scroll your mouse, the numbers change.  This happens in all four fields.  We do not want this to happen,

![image](https://user-images.githubusercontent.com/19496579/37609115-97c3d68c-2b72-11e8-82ca-73024350e450.png)

**Comment by joebhaktiarDOL** [comment] 2018-03-23 13:01
I've looked further into this and everywhere on the website, they are using this method for mouse hover. Let's discuss this in the stand up meeting on Monday.

**Comment by EStriegel** [comment] 2018-03-26 16:29
Not a bug - working as expected.  Moving to `Closed`

**Closed by EStriegel** 2018-03-26 16:29 UTC
Labels: Milestone 1, WHD QA
