### ISSUE TITLE
Bug: Registration requires clicking the "Register" button twice

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#667] opened 2018-03-06 18:25 UTC
Register a new user. click on the button to submit. The first click moves the page up. The second click submits the form.

I believe this is the same behavior across multiple buttons.

**Comment by EStriegel** [comment] 2018-03-06 21:25
Duplicate of #640.  Moving to `closed`.

**Closed by EStriegel** 2018-03-06 21:25 UTC
