### ISSUE TITLE
As a member of the 14c team, I would like to be able to change the status of an application

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#92] opened 2016-11-07 16:06 UTC
Description: Certificate Mqanager and team members can modify trhe application status, System Admin can do everything, everyone else will see as read only field

Tasks 
- [x] Create front end status dropdown with a button next to the dropdown that updates the dbase with the new status
- [x] Back end need to add status, auth check and field modifications
- [x] Test coverage 90%

Acceptance Criteria: Certificate Mqanager and team members can modify trhe application status, System Admin can do everything, everyone else will see as read only field, status dropdown will be on application summary page from wireframes in story #11 and provide update button to change the data.  For now last author and timestamp on latest change for modification/audit

**Comment by mgwalker** [comment] 2016-12-02 03:34
I made the user with email `michael.walker@gsa.gov` a certification team manager.  When I logged in as that user, I got a white page with just a `Change Password` link.  I opened the network viewer and see that it's attempting to make a call to `/api/save/24-6835693` that fails.  It also made a call to `/api/Account/Userinfo` returning this:

```json
{
    "userId": "1c04649f-fc9d-4503-abbf-667a3da9f12b",
    "email": "michael.walker@gsa.gov",
    "organizations": [
        {
            "ein": "24-6835693",
            "isAdmin": true
        }
    ],
    "roles": [
        {
            "id": "7c53db43-ea95-4536-9082-29bf4bc9203d",
            "name": "Certification Team Member"
        }
    ],
    "applicationClaims": []
}
```

I don't see any way to view applications, let alone change the status.

**Comment by jmmcnj** [comment] 2016-12-02 03:55
@mgwalker right now there are only 2 roles setup in the system, we will need to work with DoL to apply more roles/feature mappings, part of the discussion that liz and myself are having in slack, I will set your account as System Administrator and then you should be able to see everything, I can also find another account of yours and set it as Applicant really for now the only other role setup with feature mapping

**Comment by mgwalker** [comment] 2016-12-02 03:56
Ahh, that's good to know.  Thanks for clarifying!  My admin account can see everything as expected.  I'll use that one for going through these other stories.

**Comment by jmmcnj** [comment] 2016-12-02 03:59
oh yeah how otherwise were you able to set your other account as Certification Team Manager, so i guess you can set your other account as Applicant yourself then?

**Comment by mgwalker** [comment] 2016-12-02 03:59
Yeah, no trouble.  :)

**Comment by mgwalker** [comment] 2016-12-02 04:05
Since the role mappings aren't finished, should we create new user stories as part of an epic to add those roles, before we close these?

**Comment by mmurthydol** [comment] 2017-07-11 00:02
related to #142

**Comment by EStriegel** [comment] 2018-04-25 16:53
Duplicate of #46 & #49

**Closed by EStriegel** 2018-04-25 16:53 UTC
