### ISSUE TITLE
Password reset email not being sent

### ISSUE THREAD

**Issue by phirefly** [18F/dol-whd-14c#639] opened 2018-02-13 19:24 UTC
Testing password reset on 2/12. I didn't receive an email after submitting twice.

**Comment by mmurthydol** [comment] 2018-03-13 21:44
@PrabhakarThummalaDOL Please verify if this can be reproduced (if not already).

**Comment by PrabhakarThummalaDOL** [comment] 2018-03-15 18:55
@phirefly , @EStriegel  I have tested both 'Forgot Password' and 'Change Password'. 'Forgot password' is sending 'Reset Password' email and the link in the email to reset password is working fine. 'Change Password' - allows the user to change the password but does not send email. @mmurthydol mentioned that 'Change Password' should not send an email to the user.

**Comment by mmurthydol** [comment] 2018-03-16 18:27
@EStriegel I believe Change Password must not send an email to user since the user already knows that they changed password. If you do not need this feature from a business perspective, let's move this to inbox in case security brings this up.

**Comment by EStriegel** [comment] 2018-03-19 16:15
@mmurthydol Correct - an email is not required when a user changes their password while they're logged in.  Moving to `Closed` based on @PrabhakarThummalaDOL's comment above that shows the error can't be recreated.

**Closed** 2018-03-19 16:15 UTC
Labels: Milestone 1, WHD QA
