### ISSUE TITLE
BUG: issue found on WIOA, the information won't show on slider after the data has been saved 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#704] opened 2018-06-04 00:50 UTC
Bug description:
issue on https://section14cdev.dol.gov/#!/section/wioa

 The external user listed all applicable workers - paid a subminimum wage age 24 or younger.
Once the data has been entered and saved, the slider show blank. 
However, I still can apply and got the email with the attached PDF file. 

![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/2f417ed6-cb8c-4789-b3be-80280608029a)

**Comment by EStriegel** [comment] 2018-07-19 16:31
Duplicate of #680.  Closed.

**Closed as completed by EStriegel** 2018-07-19 16:31 UTC
Labels: bug, Critical
