### ISSUE TITLE
Bug: The system should not display a default selection (see screen shot). Please remove default selection. Area: Worker site/employee >Add New Employee.   Field: Productivity measure/rating for job described above

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#747] opened 2018-07-16 02:27 UTC
Bug description:
Issue: Should not have default selection. Should not default to n/a-piece rate (allow user to select)

Steps:
Worker site/employee > Add New Employee
> Select one of the workers, click ‘Edit the Employee’ 
> Then click Add New Employee ‘
> Go to the Productivity measure/rating for job described above
 field.
> System is selecting the first option by default  (n/a – piece rate). 

Fix: Do not display a default selection (see screen shot), but allow user to choose. Please remove default selection.
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/8a6c1931-e560-4906-a5f3-da27961a3467)

**Comment by EStriegel** [comment] 2018-07-26 19:32
Duplicate of #722.  Closed.

**Closed as completed by EStriegel** 2018-07-26 19:32 UTC
Labels: bug, Milestone 1
