### ISSUE TITLE
Bug:  In slider, when user inputs a $ for wage fields the entry disapears when they tab out

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#594] opened 2018-01-29 21:31 UTC
Bug description: 
In slider, when user inputs a $ for wage fields the entry disapears when they tab out.
@EStriegel please provide screenshot or information for this issue found in QA.

**Comment by davoodharun** [comment] 2018-02-13 06:19
This looks like its only an issue in IE related to <input type="number">. It works fine in chrome. However, after thinking about it, I think this is actually working as intended.. The user should not be allowed to input non-numerical characters. If a user enters a non numerical character, IE will treat that input as empty. A work around would be to change the  input type to "text".

**Comment by mmurthydol** [comment] 2018-02-13 16:31
@davoodharun (a) can we display $ as a label and leave the input as numeric. Would that solve the issue?
(b) if we change type to text, looks like you would need to filter/strip out the $ if present, validate, convert to whatever the API needs (last step probably not needed?). (a) sounds like easy fix unless I am missing something.

@EStriegel FYI

**Comment by EStriegel** [comment] 2018-02-13 16:52
The highlighted fields would require the $ label.

![image](https://user-images.githubusercontent.com/19496579/36162393-5744a1f0-10b4-11e8-91bb-c4d3072ac368.png)

**Comment by EStriegel** [comment] 2018-02-23 16:51
Completed.  Moving to `Done`

**Closed** 2018-06-08 00:31 UTC
Labels: Critical, Milestone 1, bug
