### ISSUE TITLE
Bug: API - Error message missing for required field ( EIN) for employer and this field is not part of validation process. 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#717] opened 2018-06-22 14:55 UTC
related info in #717

**Requirements**
- [ ] Add EIN validation in API methods that Save/Submit data that includes EIN.

**Comment by EStriegel** [comment] 2018-07-19 16:32
Duplicate of #756.  Closed.

**Closed as completed by EStriegel** 2018-07-19 16:32 UTC
Labels: bug, Milestone 1, Critical
