### ISSUE TITLE
 API - As an applicant, I would like to have "Name of Worker" within the add employee slider to be captured as First Name, Last Name to prevent data quality issues 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#712] opened 2018-06-20 19:01 UTC
Modify appropriate DB schema/API calls to split “Employee” table “Name” column in to “First Name”, and “Last Name”. Perhaps do not drop name column in the schema JIC, and return “First Name”, “Last Name” in the API.

**Comment by binwang89** [comment] 2018-06-20 19:44
See story #651  for reference

**Comment by PrabhakarThummalaDOL** [comment] 2018-08-15 15:08
Closed. 
Duplicate of #767.

**Closed as completed by PrabhakarThummalaDOL** 2018-08-15 15:08 UTC
