### ISSUE TITLE
Bug: Wage Data for Renewal Application,  for Piece Rate, the upload function for documentation of the methods used to determine the standard productivity is not working and user can not upload the file. 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#703] opened 2018-05-25 19:37 UTC
Bug description:
user can't upload one piece of documentation for piece rate. 
https://section14cdev.dol.gov/#!/section/wage-data

First screenshot at the top:
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/48aaa4b3-d929-4438-ac57-811f72c47edc)![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/b8df8f7b-cd25-4f76-afba-d39e809ba998)

2nd screenshot at the bottom of the page:
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/bf82c03f-bc0a-420d-8992-95309100bc37)

3rd screenshot from the developer tool:
![image.png](https://images.zenhubusercontent.com/5887af0e51aa2c305772c053/8d90aa99-17c5-4350-a8af-d78326f93dc9)

4th screenshot - if user select the hourly rate, the upload feature is working, please see below:

![image](https://user-images.githubusercontent.com/25330625/40563198-f0dadd1c-6031-11e8-9641-3a6b416be194.png)

**Comment by binwang89** [comment] 2018-05-25 19:56
I re-test it with another email account, I could not re-produce the same issue. the piece-rate option seem okay. At the end, I was able to submit the application.

**Comment by binwang89** [comment] 2018-06-04 00:39
I re-test it with the same dol email account, and i can't re-produce the same error, i think we can drop this issue.

**Comment by NathayaMDOL** [comment] 2018-07-06 16:04
This function is working fine. Couldn't re-produce the bugs.

**Comment by binwang89** [comment] 2018-07-31 19:40
@NathayaMDOL @mmurthydol  i just tried and i can replicate the issue again. please see below screenshot 
 https://section14cdev.dol.gov/#!/section/wage-data
1. create application ( Renew first)
2. go thru add your data for wage date page.
3. select the piece rate.
4. uploaded the PDF file, then deleted it 
5. change the application from Renew to New. 
6. go thru the application and add some information or data.
7. change the application from New to Renew again. 
8. go to the wage data page, the upload function button is gone. 

![image](https://user-images.githubusercontent.com/25330625/43482648-47917a42-94d7-11e8-9b44-0c050c041456.png)
![image](https://user-images.githubusercontent.com/25330625/43482678-5de1548e-94d7-11e8-8e33-f9445ca7038e.png)
![image](https://user-images.githubusercontent.com/25330625/43482707-6f887546-94d7-11e8-99af-2f4efe918c3f.png)

**Comment by binwang89** [comment] 2018-08-06 19:26
@EStriegel   Hi, Liz, could you please check this user story,  we ( @NathayaMDOL and I) could not re-produce it anymore,  even we follow the defect steps.  do you think that is low priority defect and we can work on other defect ?

**Comment by EStriegel** [comment] 2018-08-06 19:39
Cannot be reproduced.  Closed.

**Comment by mmurthydol** [comment] 2018-08-06 19:48
@EStriegel @binwang89 
Hi Liz, the accurate statement is that Michelle can reproduce the steps but Nathaya could not. The implication being may be the user might not run in to the defect often. My suggestion is that Michelle can demo the repro steps and you can decide on its priority - which is your call. If you felt this was low enough priority that we won't fix for milestone 1, let's annotate the repro steps and place this story in the icebox.
Thanks, Madhu

**Comment by mmurthydol** [comment] 2018-08-06 19:55
@EStriegel @binwang89 
Liz; Looks like Michelle cannot repro any more (I was off on this fact). She was able to repro last week. For now I will close this error. I have a feeling we have some problematic errors in file upload functionality. Hopefully we won't run in to them. Thanks and sorry for the bother both of you.

**Closed as completed by mmurthydol** 2018-08-06 19:55 UTC
Labels: bug, Critical
