### ISSUE TITLE
Bug: Email is not always firing on application submission

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#603] opened 2018-01-31 19:46 UTC
- [ ] @binwang89 Verify emails are being sent / whether error logs show email failure

Sometimes happens, need to find pattern

**Comment by jmmcnj** [comment] 2018-01-31 19:47
Madhu - further research needed to see pattern of failures if any, otherwise deeper bug review to find problems

**Comment by EStriegel** [comment] 2018-03-06 18:48
@binwang89 Can you review the error logs to see if there is a pattern for email failures?

**Comment by binwang89** [comment] 2018-03-15 21:53
@EStriegel @mmurthydol I have tested. However, I can't submit the application.  
2 issues i found when testing the 14c. 
1. The Worksite/Employee page can't show previous work site  and I can't correct the the error. 
2. while in the middle of working on the application, the system timeout message popup and asked me if i need more time.

**Comment by binwang89** [comment] 2018-03-16 20:21
@EStriegel @mmurthydol @PrabhakarThummalaDOL after i retested today (log off and log back in to 14c),  it seems the issue was not there.  I think it maybe browser  or API refresh issue. I can not reproduce the same error anymore. 

![image](https://user-images.githubusercontent.com/25330625/37542632-324d59ca-2935-11e8-945f-c3ce44c28bfe.png)

**Comment by EStriegel** [comment] 2018-04-10 19:43
Cannot reproduce.  Moving to `Closed`

**Comment by mmurthydol** [comment] 2018-06-26 22:22
@binwang89 @EStriegel Michelle/Liz: Problem must have resolved from 14c online sending emails to the logged in user instead of contact person email

**Comment by binwang89** [comment] 2018-06-27 13:00
@EStriegel @mmurthydol I have tested the application and this issue has been resolved.  I will close it.

**Closed by binwang89** 2018-06-27 13:00 UTC
Labels: Milestone 1, bug
