### ISSUE TITLE
Bug: Initial application,  in Review & Submit page, the Wage data must not be displayed. 

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#523] opened 2017-12-21 21:15 UTC
@EStriegel Liz, please confirm our understanding that this is a defect. if not please close story. In either case remove yourself from assignee list. Please review labels and change as appropriate. If needed for milestone 1, we will need to prioritize appropriately in the backlog.
 
- [x] Research spike for @davoodharun and @dciceman to figure out extent of issue and update estimate of greater than originally thought, also will notify team of the change to make clear
- [x] DOL/AIS: Establish whether UI has this information (application is initial/renewal), or whether an API call provides you this info. Please create an API story if need be. 
- [x] If UI has this info already it is a simple matter of hiding the "Wage data" info & Steven can do the work. If not, Harun will have to show Steven how to call the API and provide the info for Steve to use to hide the info.

![image](https://user-images.githubusercontent.com/25330625/34275181-18bad6bc-e66a-11e7-8ce8-e5531cfb717f.png)

![image](https://user-images.githubusercontent.com/25330625/34275155-fad9c298-e669-11e7-8754-f2258b328b81.png)

**Comment by mmurthydol** [comment] 2017-12-22 04:14
duplicate of #524. Closing this issue.

**Comment by EStriegel** [comment] 2018-02-20 23:26
Complete.  Moved to `Done`

**Closed** 2018-06-08 00:39 UTC
Labels: Critical, Milestone 1, WHD QA, bug
