### ISSUE TITLE
As a Parent, I want to know if my child's employer holds a certificate so that I know the employer has the right to pay less than the minimum wage.

### ISSUE THREAD

**Issue by jmmcnj** [18F/dol-whd-14c#36] opened 2016-09-26 15:45 UTC
similar to previous requirement on public facing site, need to provide ability to search certification status by state or employer name

**Comment by EStriegel** [comment] 2017-03-10 17:03
Duplicate of item #18.

**Closed by EStriegel** 2017-03-10 17:03 UTC
Labels: Admin Interface
