### ISSUE TITLE
API2 -  API - As an applicant, I would like to have "Name of Worker" within the add employee slider to be captured as First Name, Last Name to prevent data quality issues

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#714] opened 2018-06-20 19:07 UTC
TODO - to be discussed.
Once API is connected to UI correctly, drop the “Name” column from DB and API. Blocked by the UI story

**Comment by binwang89** [comment] 2018-06-20 19:45
See story #651 for reference

**Comment by PrabhakarThummalaDOL** [comment] 2018-08-15 15:08
Closed. 
Duplicate of #767.

**Closed as completed by PrabhakarThummalaDOL** 2018-08-15 15:08 UTC
