### ISSUE TITLE
Need to display a message on click 'Submit 14c certificate' when one (or more) pages Needs review.

### ISSUE THREAD

**Issue by PrabhakarThummalaDOL** [18F/dol-whd-14c#648] opened 2018-02-15 21:33 UTC
When user clicks on 'Submit 14c Certification Application' when one or more pages 'Needs review', the button is changed to 'Loading' but (looks like) the application is not doing anything. User can still go back to those pages.

**Comment by mmurthydol** [comment] 2018-02-20 22:53
duplicate of #504. Closing this issue.

**Closed by mmurthydol** 2018-02-20 22:53 UTC
