### ISSUE TITLE
Bug: Add Employee - Panel Open - " Can "n/a - piece rate" not be a default selection under "Productivity measure/rating for job described above"  Neither radio button should be selected when a user opens the slider.

### ISSUE THREAD

**Issue by binwang89** [18F/dol-whd-14c#600] opened 2018-01-29 22:11 UTC
Bug description:

in Chrome, Add   Employee - Panel Open - " Can "n/a - piece rate" not be a   default selection under "Productivity measure/rating for job described   above"  Neither radio button   should be selected when a user opens the slider.
@EStriegel please provide the screenshot or information related to this issue found in QA.

**Comment by NathayaMDOL** [comment] 2018-07-17 18:10
@binwang89 , @PrabhakarThummalaDOL 
This story is duplicated with #722 which has been fixed and pushed to dev. @binwang89 , Can you please confirm?
Branch name: "whd-aqa-722-nmankong-pageaddemployees-radiobutton-productivitymeasure"

**Comment by EStriegel** [comment] 2018-07-26 19:31
Duplicate of #722.  Closed.

**Closed by EStriegel** 2018-07-26 19:31 UTC
Labels: Critical, Milestone 1, WHD QA, bug
