### ISSUE TITLE
Document Upload

### ISSUE THREAD

**Issue by EStriegel** [18F/dol-whd-14c#102] opened 2016-11-16 18:32 UTC
After uploading a document, the applicant is unable to click on the document link to view/download the uploaded file.  The following error message is received.

![image](https://cloud.githubusercontent.com/assets/19496579/20360266/0f386cca-ac01-11e6-8261-11de1988dab8.png)

**Comment by MrMatt57** [comment] 2016-11-28 15:26
I am unable to reproduce this issue.  I was able to upload and download the file.

**Comment by EStriegel** [comment] 2016-11-28 16:37
@MrMatt57 At the bottom of the Wage Data section, I am able to upload but not download and view the document ("Attach all documents of the methods used to determine the standard productivity and the piece rate").  When I click on the uploaded document, I get the following error:

![image](https://cloud.githubusercontent.com/assets/19496579/20676743/d33c680e-b55e-11e6-9c72-5e9e87b910fc.png)


The upload/download/view appears to work within the Employer section for SCA contracts and within the Wage Data section for prevailing wage surveys.

**Comment by MrMatt57** [comment] 2016-11-28 18:09
This was a deployment issue where the files were being reset each deployment.  This was fixed in https://github.com/AppliedIS/dol-whd-14c/pull/172

To test, you will need to delete any existing attachments and reupload them.   Any saved application attachments will just be a reference to a file that does not exist.

**Comment by binwang89** [comment] 2017-07-31 14:50
when testing the 14c, after I had uploaded the sample file in the Wage Data section, no way I can verify if the file upload was completed or unsuccessfully.

**Comment by mmurthydol** [comment] 2017-09-07 00:04
@EStriegel I noticed an error on our Web Server. This feature should work now. @binwang89 and myself verified this feature works. Once you verify it, we can close this defect before vendor starts work.

**Closed** 2017-10-11 05:26 UTC
Labels: bug, Milestone 1, Sprint-0
